name = "mcp-memory"
main = "src/index.js"
compatibility_date = "2025-07-24"

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "src"

[vars]
SUPABASE_URL = "https://shxfosnnaoxzscrhvkat.supabase.co"

[triggers]
crons = []